OTP_TYPE_UNSPECIFIED = 0
OTP_TYPE_HOTP = 1
OTP_TYPE_TOTP = 2

ALGORITHM_UNSPECIFIED = 0
ALGORITHM_SHA1 = 1
ALGORITHM_SHA256 = 2
ALGORITHM_SHA512 = 3
ALGORITHM_MD5 = 4

DIGIT_COUNT_UNSPECIFIED = 0
DIGIT_COUNT_SIX = 1
DIGIT_COUNT_EIGHT = 2

OTP_TYPE = {
    OTP_TYPE_UNSPECIFIED: 'totp',
    OTP_TYPE_HOTP: 'hotp',
    OTP_TYPE_TOTP: 'totp'
}

OTP_ALGORITHM = {
    ALGORITHM_UNSPECIFIED: 'SHA1',
    ALGORITHM_SHA1: 'SHA1',
    ALGORITHM_SHA256: 'SHA256',
    ALGORITHM_SHA512: 'SHA512',
    ALGORITHM_MD5: 'MD5'
}

OTP_DIGIT = {
    DIGIT_COUNT_UNSPECIFIED: 6,
    DIGIT_COUNT_SIX: 6,
    DIGIT_COUNT_EIGHT: 8
}
