# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: otpauth-migration.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17otpauth-migration.proto\x12\x11otpauth_migration\"\xd1\x05\n\x07Payload\x12@\n\x0eotp_parameters\x18\x01 \x03(\x0b\x32(.otpauth_migration.Payload.OtpParameters\x12\x0f\n\x07version\x18\x02 \x01(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x04 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x01(\x05\x1a\xb7\x04\n\rOtpParameters\x12\x0e\n\x06secret\x18\x01 \x01(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06issuer\x18\x03 \x01(\t\x12\x45\n\talgorithm\x18\x04 \x01(\x0e\x32\x32.otpauth_migration.Payload.OtpParameters.Algorithm\x12\x43\n\x06\x64igits\x18\x05 \x01(\x0e\x32\x33.otpauth_migration.Payload.OtpParameters.DigitCount\x12>\n\x04type\x18\x06 \x01(\x0e\x32\x30.otpauth_migration.Payload.OtpParameters.OtpType\x12\x0f\n\x07\x63ounter\x18\x07 \x01(\x04\"y\n\tAlgorithm\x12\x19\n\x15\x41LGORITHM_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x41LGORITHM_SHA1\x10\x01\x12\x14\n\x10\x41LGORITHM_SHA256\x10\x02\x12\x14\n\x10\x41LGORITHM_SHA512\x10\x03\x12\x11\n\rALGORITHM_MD5\x10\x04\"U\n\nDigitCount\x12\x1b\n\x17\x44IGIT_COUNT_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x44IGIT_COUNT_SIX\x10\x01\x12\x15\n\x11\x44IGIT_COUNT_EIGHT\x10\x02\"I\n\x07OtpType\x12\x18\n\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\x11\n\rOTP_TYPE_HOTP\x10\x01\x12\x11\n\rOTP_TYPE_TOTP\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'otpauth_migration_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PAYLOAD']._serialized_start=47
  _globals['_PAYLOAD']._serialized_end=768
  _globals['_PAYLOAD_OTPPARAMETERS']._serialized_start=201
  _globals['_PAYLOAD_OTPPARAMETERS']._serialized_end=768
  _globals['_PAYLOAD_OTPPARAMETERS_ALGORITHM']._serialized_start=485
  _globals['_PAYLOAD_OTPPARAMETERS_ALGORITHM']._serialized_end=606
  _globals['_PAYLOAD_OTPPARAMETERS_DIGITCOUNT']._serialized_start=608
  _globals['_PAYLOAD_OTPPARAMETERS_DIGITCOUNT']._serialized_end=693
  _globals['_PAYLOAD_OTPPARAMETERS_OTPTYPE']._serialized_start=695
  _globals['_PAYLOAD_OTPPARAMETERS_OTPTYPE']._serialized_end=768
# @@protoc_insertion_point(module_scope)
